CREATE MEMORY TABLE T_USER_CREATE_REQUEST (USE_ID_C VARCHAR(36) NOT NULL PRIMARY KEY, USE_IDROLE_C VARCHAR(36) NOT NULL, USE_USERNAME_C VARCHAR(50) NOT NULL, USE_PASSWORD_C VARCHAR(100) NOT NULL, USE_EMAIL_C VARCHAR(100) NOT NULL, USE_STORAGEQUOTA_N BIGINT NOT NULL, REQ_STATUS_C VARCHAR(20) NOT NULL, REQ_CREATORID_C VARCHAR(36), REQ_REVIEWERID_C VARCHAR(36), USE_CREATEDATE_D DATETIME NOT NULL, REQ_REVIEWDATE_D DATETIME, REQ_REASON_C VARCHAR(500));

-- Update the database version
update T_CONFIG set CFG_VALUE_C = '32' where CFG_ID_C = 'DB_VERSION';